### ISSUE TITLE
[uwebsockets] OSV-2021-453.yaml seems wrong

### ISSUE THREAD

**Issue by alexhultman** [google/oss-fuzz-vulns#15]
https://github.com/google/oss-fuzz-vulns/blob/main/vulns/uwebsockets/OSV-2021-453.yaml

The version range is from v19 to v20.8. This makes no sense since the issue does not reproduce in v20.8. The fixed commit is not in master branch, it has been reset (probably because a better fix replaced it) yet OSS-Fuzz links to that commit and still considers latest version v20.8 broken.

I can't trigger the issue on OSS-Fuzz "dashboard" and now some other company has created an CVE which claims version v19 to v20.8 is broken with a high severity issue which is not the case.

How to fix this?

**Comment by alexhultman** [comment]
I have tested the reproducing test case and it does trigger the crash between v19.0.0a4 and v19.0.0a5, so the version range of v19 up to latest v20.8 is wrong.

**Comment by oliverchang** [comment]
Sorry for the inaccuracy here. Our list of affected versions are automatically determined from the introduced and fixed commits. Our automation infra based it off https://github.com/uNetworking/uWebSockets/commit/4e4fd20b8ce03b30810cdb49b6237fb475c5ae05, which causes confusion because it no longer exists.

Would you be able to help point to the actual fix commit for this?

**Comment by alexhultman** [comment]
No problem, I can go through them and find the real fix

**Comment by alexhultman** [comment]
Fix is https://github.com/uNetworking/uWebSockets/commit/1507f3f98abf6bb56cd5bb26de0776a9e2c2cf36

Offender is https://github.com/uNetworking/uWebSockets/commit/7b330e9e03102ad75b102c9bb75bba573dc70045

**Comment by oliverchang** [comment]
Thanks a bunch @alexhultman ! I updated this in https://github.com/google/oss-fuzz-vulns/commit/bac99b43d2ec81634e54f66ccfc0705657ba12a5
